id: cba4e40b62b64defa2b3b020239e1246
initial_creation_type: ocr
source_metadata:
  volumes:
    f4179c087d234a62ab3d590330a137d2:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ཞིབ་མོ་རྣམ་པར་འཐག་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1605
      volume_number: 57
